import film from '../images/film.jpg';
import film2 from '../images/film2.jpg';

const movies = [
    {"id":1,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":2,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film2},
    {"id":3,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":4,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film2},
    {"id":5,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":6,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film2},
    {"id":7,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":8,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film2},
    {"id":9,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":10,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film2},
    {"id":11,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":12,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":13,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":14,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":15,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":16,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":17,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},

]

const savedMovies = [
    {"id":1,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":2,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},
    {"id":3,
        "name":"33 слова о дизайне",
        "duration":"1ч42м",
        "image": film},

]

export {movies, savedMovies}
